// Generated by CoffeeScript 1.8.0
(function() {
  var menu;

  menu = [['bold', '𝐁', 'Bold'], ['italic', '𝐼', 'Italic'], ['blockquote', '’’', 'Quote'], ['insertUnorderedList', '•', 'Unordered list'], ['insertOrderedList', '①', 'Ordered list'], ['p', 'p', 'Paragraph'], ['superscript', '¹', 'Superscript'], ['subscript', '₁', 'Subscript'], ['h1', 'h1', 'Title 1'], ['h2', 'h2', 'Title 2'], ['h3', 'h3', 'Title 3'], ['undo', '↶', 'Undo'], ['redo', '↷', 'Redo'], ['source', '<>', 'Source']];

  addEventListener('DOMContentLoaded', function() {
    var textarea, _i, _len, _ref, _results;
    _ref = document.querySelectorAll('textarea[accept=html]');
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      textarea = _ref[_i];
      _results.push((function(textarea) {
        var div, icon, name, role, ul, _fn, _j, _len1, _ref1;
        ul = document.createElement('ul');
        ul.style.fontSize = '0.8em';
        ul.style.margin = '0.25em 0';
        ul.style.opacity = '0.8';
        ul.style.padding = '0';
        _fn = function(role) {
          var a, li;
          li = document.createElement('li');
          li.style.display = 'inline-block';
          a = document.createElement('a');
          a.setAttribute('href', 'javascript:void(0)');
          a.title = name;
          a.text = icon;
          a.style.textDecoration = 'none';
          a.style.color = 'inherit';
          a.style.padding = '0.5em';
          if (role === 'source') {
            a.addEventListener('click', function() {
              var _ref1;
              return _ref1 = [div.style.display, textarea.style.display], textarea.style.display = _ref1[0], div.style.display = _ref1[1], _ref1;
            });
          } else if (role === 'h1' || role === 'h2' || role === 'h3' || role === 'h4' || role === 'h5' || role === 'h6' || role === 'p' || role === 'blockquote') {
            a.addEventListener('click', function() {
              return document.execCommand('formatBlock', false, role);
            });
          } else {
            a.addEventListener('click', function() {
              return document.execCommand(role, false, null);
            });
          }
          li.appendChild(a);
          return ul.appendChild(li);
        };
        for (_j = 0, _len1 = menu.length; _j < _len1; _j++) {
          _ref1 = menu[_j], role = _ref1[0], icon = _ref1[1], name = _ref1[2];
          _fn(role);
        }
        div = document.createElement('div');
        div.innerHTML = textarea.value;
        div.setAttribute('contenteditable', 'true');
        textarea.parentNode.insertBefore(ul, textarea);
        textarea.parentNode.insertBefore(div, textarea);
        textarea.style.display = 'none';
        textarea.addEventListener('input', function() {
          return div.innerHTML = textarea.value;
        });
        return div.addEventListener('input', function() {
          return textarea.value = div.innerHTML;
        });
      })(textarea));
    }
    return _results;
  });

}).call(this);
